version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      pre:
        - cmd: echo "Configuring compilers"
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++

archives:
  - format: tar.gz

checksum:
  name_template: checksums.txt
