version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: windows
    env:
      - CGO_ENABLED=1
    goos: [windows]
    goarch: [amd64]

archives:
  - format: zip

checksum:
  name_template: checksums.txt

release:
  replace_existing_artifacts: true