version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: windows
    if: '{{ eq .Os "windows" }}'
    env:
      - CGO_ENABLED=1
    goos: [windows]
    goarch: [amd64]

  - id: linux
    if: '{{ eq .Os "linux" }}'
    env:
      - CGO_ENABLED=1
    goos: [linux]
    goarch: [amd64, arm64]

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
